name: Shell commands
on: [push]
jobs:
  shell-en-python:
    runs-on: ubuntu-latest
    steps:
      - name: echoString
        run: echo "Hola desde yaml"
      - name: mutiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python

  shell-en-windows:
    runs-on: windows-latest
    needs: shell-en-python
    steps:
      - name: Powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
