name: Shell commands
on: [push]
jobs:
  nombre-del-job:
    runs-on: ubuntu-latest
    steps:
      - name: echoString
        run: echo "Hola desde yaml"
      - name: mutiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
        
  shell-en-windows:
    runs-on: windows-latest
    steps:
      - name: Powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
